baseURL      = 'https://blikq.github.io/portfolio'
languageCode = 'en-us'
title        = 'My Portfolio'


[params]
  description = "Al-ameen Musa personal website"
  keywords    = "Alameen Musa, personal website, blog, portfolio"

  [params.author]
    name = 'Al-ameen Musa'


# Add theme using Hugo modules
[module]
  [[module.imports]]
    path = "github.com/hugo-porto/theme"
